### ISSUE TITLE
Stylix GIF mkAnimation missing

### ISSUE THREAD

**Issue by antidoid** [SomeGuyNamedMy/users#1]
Hey, I was trying your config, and while static wallpapers work flawlessly, when I tried GIF wallpapers, I got the following error: 
```
error:
       … while evaluating a branch condition

         at /nix/store/vby8c3909sglr03fxkclkly29vs49ncy-source/lib/lists.nix:57:9:

           56|       fold' = n:
           57|         if n == len
             |         ^
           58|         then nul

       … while calling the 'length' builtin

         at /nix/store/vby8c3909sglr03fxkclkly29vs49ncy-source/lib/lists.nix:55:13:

           54|     let
           55|       len = length list;
             |             ^
           56|       fold' = n:

       (stack trace truncated; use '--show-trace' to show the full trace)

       error: attribute 'mkAnimation' missing

       at /nix/store/4h1nnp3yvjvg4jh1hirngfhdr2rcbfhi-source/home.nix:71:17:

           70|
           71|     wallpaper = config.lib.stylix.mkAnimation {
             |                 ^
           72|         animation = ../../Downloads/lofi-cafe.gif;
```

I'm not on a Non-NixOS system, and I'm using home manager with flakes for configuration.

Any help would be much appreciated, Thank you.

**Comment by SomeGuyNamedMay** [comment]
didnt know anyone was using my config lol, it should work now i believe

**Comment by antidoid** [comment]
Might be a silly question but here goes
Was it supposed to put a static wallpaper from that gif or was it gonna be a dynamic gif wallpaper because I got a static one and was hoping for a gif.

PS: I'm new to nix

**Comment by SomeGuyNamedMay** [comment]
did you update the hole git repo? cause this config uses my fork of stylix that enables this animation support

**Comment by SomeGuyNamedMay** [comment]
also are you using sway like in my config?

**Comment by antidoid** [comment]
I updated the whole git repo, and I use GNOME not sway, could that be an issue?

**Comment by SomeGuyNamedMay** [comment]
yup, gnome only works with the static and slideshow wallpapers

**Comment by antidoid** [comment]
Okay, thanks for letting me know.
